const euro_countries = [
  {
    country: 'Albania',
    capital: 'Tirana',
    coordinates: { lat: 41.3275, lon: 19.8187 },
    fact: 'Albania has more than 750,000 bunkers.',
  },
  {
    country: 'Andorra',
    capital: 'Andorra la Vella',
    coordinates: { lat: 42.5063, lon: 1.5218 },
    fact: 'Andorra is the sixth smallest nation in Europe.',
  },
  {
    country: 'Armenia',
    capital: 'Yerevan',
    coordinates: { lat: 40.1792, lon: 44.4991 },
    fact: 'Armenia was the first country to adopt Christianity as its state religion.',
  },
  {
    country: 'Austria',
    capital: 'Vienna',
    coordinates: { lat: 48.2082, lon: 16.3738 },
    fact: 'Austria is the only country other than Germany where the official language is German.',
  },
  {
    country: 'Azerbaijan',
    capital: 'Baku',
    coordinates: { lat: 40.4093, lon: 49.8671 },
    fact: 'Azerbaijan is known as the Land of Fire.',
  },
  {
    country: 'Belarus',
    capital: 'Minsk',
    coordinates: { lat: 53.9045, lon: 27.5615 },
    fact: 'Belarus is known for its diverse architecture and deep forests.',
  },
  {
    country: 'Belgium',
    capital: 'Brussels',
    coordinates: { lat: 50.8503, lon: 4.3517 },
    fact: 'Belgium produces more than 220,000 tons of chocolate per year.',
  },
  {
    country: 'Bosnia and Herzegovina',
    capital: 'Sarajevo',
    coordinates: { lat: 43.8563, lon: 18.4131 },
    fact: 'Sarajevo hosted the 1984 Winter Olympics.',
  },
  {
    country: 'Bulgaria',
    capital: 'Sofia',
    coordinates: { lat: 42.6977, lon: 23.3219 },
    fact: 'Bulgaria is the oldest country in Europe that hasn’t changed its name since it was first established.',
  },
  {
    country: 'Croatia',
    capital: 'Zagreb',
    coordinates: { lat: 45.815, lon: 15.9819 },
    fact: 'The Dalmatian dog is originally from Croatia.',
  },
  {
    country: 'Cyprus',
    capital: 'Nicosia',
    coordinates: { lat: 35.1856, lon: 33.3823 },
    fact: 'Cyprus is the only foreign venue at which an English Royal Wedding has been hosted.',
  },
  {
    country: 'Czech Republic',
    capital: 'Prague',
    coordinates: { lat: 50.0755, lon: 14.4378 },
    fact: 'The Czech Republic is the castle capital of the world.',
  },
  {
    country: 'Denmark',
    capital: 'Copenhagen',
    coordinates: { lat: 55.6761, lon: 12.5683 },
    fact: 'Denmark has 443 named islands.',
  },
  {
    country: 'Estonia',
    capital: 'Tallinn',
    coordinates: { lat: 59.437, lon: 24.7536 },
    fact: 'Estonia is one of the least populated countries in Europe.',
  },
  {
    country: 'Finland',
    capital: 'Helsinki',
    coordinates: { lat: 60.1699, lon: 24.9384 },
    fact: 'Finland has over 3 million saunas.',
  },
  {
    country: 'France',
    capital: 'Paris',
    coordinates: { lat: 48.8566, lon: 2.3522 },
    fact: 'France is the most visited country in the world.',
  },
  {
    country: 'Georgia',
    capital: 'Tbilisi',
    coordinates: { lat: 41.7151, lon: 44.8271 },
    fact: 'Georgia is considered the birthplace of wine.',
  },
  {
    country: 'Germany',
    capital: 'Berlin',
    coordinates: { lat: 52.52, lon: 13.405 },
    fact: 'Germany is known for its rich history in literature, music, and art.',
  },
  {
    country: 'Greece',
    capital: 'Athens',
    coordinates: { lat: 37.9838, lon: 23.7275 },
    fact: 'Greece is considered the birthplace of Western civilization.',
  },
  {
    country: 'Hungary',
    capital: 'Budapest',
    coordinates: { lat: 47.4979, lon: 19.0402 },
    fact: 'Budapest has one of the oldest metro systems in the world.',
  },
  {
    country: 'Iceland',
    capital: 'Reykjavik',
    coordinates: { lat: 64.1466, lon: -21.9426 },
    fact: 'Iceland is known as the Land of Fire and Ice due to its volcanoes and glaciers.',
  },
  {
    country: 'Ireland',
    capital: 'Dublin',
    coordinates: { lat: 53.3498, lon: -6.2603 },
    fact: 'Ireland is famous for its lush green landscapes and folklore.',
  },
  {
    country: 'Italy',
    capital: 'Rome',
    coordinates: { lat: 41.9028, lon: 12.4964 },
    fact: 'Rome is home to the Colosseum, an ancient amphitheater.',
  },
  {
    country: 'Kosovo',
    capital: 'Pristina',
    coordinates: { lat: 42.6629, lon: 21.1655 },
    fact: 'Kosovo declared its independence from Serbia in 2008.',
  },
  {
    country: 'Latvia',
    capital: 'Riga',
    coordinates: { lat: 56.9496, lon: 24.1052 },
    fact: 'Riga is known for its well-preserved medieval Old Town.',
  },
  {
    country: 'Liechtenstein',
    capital: 'Vaduz',
    coordinates: { lat: 47.141, lon: 9.5215 },
    fact: "Liechtenstein is one of the world's smallest countries.",
  },
  {
    country: 'Lithuania',
    capital: 'Vilnius',
    coordinates: { lat: 54.6872, lon: 25.2797 },
    fact: 'Vilnius has a UNESCO-listed Old Town with historic architecture.',
  },
  {
    country: 'Luxembourg',
    capital: 'Luxembourg City',
    coordinates: { lat: 49.6116, lon: 6.1319 },
    fact: 'Luxembourg City is one of the wealthiest cities in the world.',
  },
  {
    country: 'Malta',
    capital: 'Valletta',
    coordinates: { lat: 35.8989, lon: 14.5146 },
    fact: 'Malta is known for its historic sites and clear waters.',
  },
  {
    country: 'Moldova',
    capital: 'Chisinau',
    coordinates: { lat: 47.0104, lon: 28.8638 },
    fact: 'Moldova is famous for its vineyards and wine production.',
  },
  {
    country: 'Monaco',
    capital: 'Monaco',
    coordinates: { lat: 43.7384, lon: 7.4246 },
    fact: 'Monaco is the second-smallest country in the world.',
  },
  {
    country: 'Montenegro',
    capital: 'Podgorica',
    coordinates: { lat: 42.4304, lon: 19.2594 },
    fact: 'Montenegro has a stunning coastline along the Adriatic Sea.',
  },
  {
    country: 'Netherlands',
    capital: 'Amsterdam',
    coordinates: { lat: 52.3676, lon: 4.9041 },
    fact: 'The Netherlands is famous for its tulip fields and windmills.',
  },
  {
    country: 'North Macedonia',
    capital: 'Skopje',
    coordinates: { lat: 41.9965, lon: 21.4314 },
    fact: 'Skopje has a blend of historical and modern architecture.',
  },
  {
    country: 'Norway',
    capital: 'Oslo',
    coordinates: { lat: 59.9139, lon: 10.7522 },
    fact: 'Norway is known for its stunning fjords and natural beauty.',
  },
  {
    country: 'Poland',
    capital: 'Warsaw',
    coordinates: { lat: 52.2297, lon: 21.0122 },
    fact: 'Poland has a rich history and is famous for its pierogi.',
  },
  {
    country: 'Portugal',
    capital: 'Lisbon',
    coordinates: { lat: 38.7369, lon: -9.1427 },
    fact: "Portugal is known for its delicious pastries called 'pastéis de nata.'",
  },
  {
    country: 'Romania',
    capital: 'Bucharest',
    coordinates: { lat: 44.4268, lon: 26.1025 },
    fact: 'Romania is home to one of the heaviest buildings in the world, the Palace of the Parliament.',
  },
  {
    country: 'Russia',
    capital: 'Moscow',
    coordinates: { lat: 55.7558, lon: 37.6176 },
    fact: 'Russia is the largest country in the world, spanning across two continents.',
  },
  {
    country: 'San Marino',
    capital: 'San Marino',
    coordinates: { lat: 43.9424, lon: 12.4578 },
    fact: "San Marino is one of the world's oldest republics.",
  },
  {
    country: 'Serbia',
    capital: 'Belgrade',
    coordinates: { lat: 44.7866, lon: 20.4489 },
    fact: 'Belgrade is known for its vibrant nightlife.',
  },
  {
    country: 'Slovakia',
    capital: 'Bratislava',
    coordinates: { lat: 48.1486, lon: 17.1077 },
    fact: 'Slovakia is known for its beautiful Tatra Mountains.',
  },
  {
    country: 'Slovenia',
    capital: 'Ljubljana',
    coordinates: { lat: 46.0569, lon: 14.5058 },
    fact: 'Slovenia has one of the highest densities of caves and karst landscapes in the world.',
  },
  {
    country: 'Spain',
    capital: 'Madrid',
    coordinates: { lat: 40.4168, lon: -3.7038 },
    fact: 'Spain is famous for its lively festivals, including La Tomatina and Running of the Bulls.',
  },
  {
    country: 'Sweden',
    capital: 'Stockholm',
    coordinates: { lat: 59.3293, lon: 18.0686 },
    fact: 'Sweden is home to the Nobel Prize, awarded annually in Stockholm.',
  },
  {
    country: 'Switzerland',
    capital: 'Bern',
    coordinates: { lat: 46.948, lon: 7.4474 },
    fact: 'Switzerland is famous for its stunning Alpine landscapes and Swiss watches.',
  },
  {
    country: 'Turkey',
    capital: 'Ankara',
    coordinates: { lat: 39.9334, lon: 32.8597 },
    fact: 'Turkey is known for its unique location, straddling both Europe and Asia, with a rich cultural heritage influenced by both continents.',
  },
  {
    country: 'Ukraine',
    capital: 'Kyiv',
    coordinates: { lat: 50.4501, lon: 30.5234 },
    fact: 'Ukraine is known for its diverse cuisine, including delicious borscht and pierogi.',
  },
  {
    country: 'United Kingdom',
    capital: 'London',
    coordinates: { lat: 51.5074, lon: -0.1278 },
    fact: 'The UK is famous for its historical landmarks, such as the Tower of London and Buckingham Palace.',
  },
  {
    country: 'Vatican City',
    capital: 'Vatican City',
    coordinates: { lat: 41.9029, lon: 12.4534 },
    fact: "Vatican City is the smallest independent state in the world, and it's the spiritual and administrative center of the Roman Catholic Church.",
  },
];

export default euro_countries;